version: '3.8'

services:
  postgres:
    container_name: nest-postgres
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/pg:/data/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest
      - PGDATA=/data/postgres