version: '3.8'
name: rc-nodejs-05
services:
  postgres:
    container_name: nest-postgres
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/pg:/data/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest
      - PGDATA=/data/postgres

  cache:
    container_name: nest-clean-cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data